### PR TITLE
Added possibility to override root node to LightingState.

### PR DESCRIPTION
**Pull request by JavaSaBr**
Added possibility to override root node to LightingState.

### CODE REVIEW

**Comment by pspeed42** [comment]
You closed this because you changed your mind or?

**Comment by JavaSaBr** [comment]
I have a lot of changes, I think you don't want to approve it :)

**Comment by pspeed42** [comment]
Could be.  Especially the change to protected fields since that's a big nasty ugly super-bad awful antipattern.

**Comment by JavaSaBr** [comment]
I have added to support clone/save/load your states, it includes a lot of big changes...

**Comment by JavaSaBr** [comment]
You can look at the result diff
https://github.com/Simsilica/SimFX/pull/2

**Pull request closed without merging**
